language: python
cache: pip
install:
  - pip install tox

jobs:
  include:
    - stage: syntax
      script: tox
      python: 3.6
      dist: xenial
      sudo: true
      env: TOXENV=syntax
    - stage: test
      script: tox
      python: 3.5
      dist: xenial
      sudo: true
      env: TOXENV=py35
    - stage: test
      script: tox
      python: 3.6
      dist: xenial
      sudo: true
      env: TOXENV=py36
    - stage: test
      script: tox
      python: 3.7
      dist: xenial
      sudo: true
      env: TOXENV=py37
