language: python
dist: xenial
sudo: false
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.6
      dist: xenial
    - python: 3.5
      dist: xenial
install:
  pip install tox-travis

jobs:
  include:
    - stage: lint
      script: tox
      env: TOXENV=lint

    - stage: test
      script: tox